# Generated by Django 3.0 on 2019-12-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wikiPagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundOneTitle', models.CharField(max_length=100)),
                ('fundOneURL', models.CharField(max_length=100)),
                ('fundTwoTitle', models.CharField(max_length=100)),
                ('fundTwoURL', models.CharField(max_length=100)),
                ('fundThreeTitle', models.CharField(max_length=100)),
                ('fundThreeURL', models.CharField(max_length=100)),
                ('fundFourTitle', models.CharField(max_length=100)),
                ('fundFourURL', models.CharField(max_length=100)),
            ],
        ),
    ]
