# Generated by Django 3.0 on 2019-12-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipagesmodel',
            name='fundFourTitle',
        ),
        migrations.RemoveField(
            model_name='wikipagesmodel',
            name='fundOneTitle',
        ),
        migrations.RemoveField(
            model_name='wikipagesmodel',
            name='fundThreeTitle',
        ),
        migrations.RemoveField(
            model_name='wikipagesmodel',
            name='fundTwoTitle',
        ),
    ]
