# Generated by Django 3.0 on 2019-12-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funds', '0003_auto_20191213_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipagesmodel',
            name='fundFourTitle',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikipagesmodel',
            name='fundOneTitle',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikipagesmodel',
            name='fundThreeTitle',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikipagesmodel',
            name='fundTwoTitle',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
    ]
